-- PanPals local seed data.
--
-- catalog_products, seeded from a license-clean dataset (D17):
--   Dataset:   Cosmetics datasets
--   Author:    kingabzpro (Kaggle)
--   URL:       https://www.kaggle.com/datasets/kingabzpro/cosmetics-datasets
--   License:   MIT
--   Retrieved: 2026-07-22
--   Full provenance: docs/CATALOG-PROVENANCE.md
--
-- Regenerate: place the dataset CSV at data/catalog_raw.csv (gitignored,
-- not committed) and run `node scripts/build-catalog-seed.mjs`.
-- 388 rows across 34 source types, capped at
-- 12 rows/type for a demo-sized catalog.

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('The Ordinary', 'Glycolic Acid 7% Toning Solution', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Roche-Posay', 'Toleriane Hydrating Gentle Face Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Ordinary', 'Niacinamide 10% + Zinc 1%', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Youth To The People', 'Superfood Antioxidant Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('COSRX', 'Low pH Good Morning Gel Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Roche-Posay', 'Toleriane Purifying Foaming Face Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Ordinary', 'Azelaic Acid Suspension 10%', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('COSRX', 'Advanced Snail 92 All In One Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Ordinary', 'Natural Moisturizing Factors + HA', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Beauty of Joseon', 'Relief Sun : Rice + Probiotics', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Paula''s Choice', 'Skin Perfecting 2% BHA Liquid Exfoliant', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('CeraVe', 'Renewing SA Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('CeraVe', 'Moisturizing Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('CeraVe', 'Daily Moisturizing Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Ordinary', 'Hyaluronic Acid 2% + B5', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('CeraVe', 'Foaming Facial Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('A''Pieu', 'Pure Block Natural Waterproof Sun Cream SPF50+ PA+++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Anna Sui', 'Liquid Foundation', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Burt''s Bees', 'BB Cream with SPF 15', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soap & Glory', 'Heel Genius Moisturizing Foot Cream', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Person & Covey, Inc.', 'Solbar Avo SPF 35', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Bi-Facil Double-Action Eye Makeup Remover', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Daily Essentials Mattifying Day Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kose Cosmeport', 'Sekkisei Clear Wellness UV Sunscreen Essence Gel SPF 50+ PA++++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('VZK', 'Sun Protection Cream SPF 50+ Anti-Age', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Bed Head by TIGI', 'Some Like It Hot Heat Protection Spray for Heat Styling', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Gehwol', 'Warming Balm', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Gehwol', 'Fusskraft Red', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kracie', 'Ichikami Smooth and Sleek Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Person & Covey, Inc.', 'Solbar Fifty SPF 50', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Clarins', 'UV Plus Anti-Pollution Sunscreen SPF 50', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Person & Covey, Inc.', 'DHS Color Safe Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('BCL', 'AHA Cleansing Research Oil Cleansing Pore Clear', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Daily Essentials Refreshing Facial Wash Gel', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kracie', 'Tabi no Yado Clear - Assorted Series Pack (Kusatsu, Noboribetsu, Hakone, & Beppu)', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Katy Perry Fragrances', 'Mad Potion Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Bed Head by TIGI', 'Recovery Moisturizing Shampoo for Dry Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Jack Black', 'Pure Clean Daily Facial Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', '3 in 1 Repair Hand Cream', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Paris Hilton Fragrances', 'Siren Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Wardah', 'UV Shield Aqua Fresh Essence SPF 50 PA++++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shiseido', 'Revitalizing Treatment Softener', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('LUSH', 'Revive Hair Moisturizer', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('René Furterer', 'Lissea Smoothing Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lakme', 'Blush & Glow Strawberry Freshness Gel Face Wash With Strawberry Extracts', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('King of Shaves', 'Refreshing Face Wash', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Mane ''n Tail', 'Herbal Gro Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Pantene', '3 Minute Miracle Moisture Renewal Daily Intensive Conditioner with Biotin', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dr. Oracle', 'A-Thera Sunblock SPF 50', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Uriage', 'Roséliane CC Cream SPF50+', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('Neutrogena', 'Revitalizing Lip Balm SPF 20', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Neutrogena', 'Pure & Free Baby Sunscreen Stick SPF 50', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Blistex', 'Deep Renewal Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Eau Thermale Avène', 'Cicalfate Lips Repair Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ryor', 'Denní Krém S Amarantovým Olejem A Hedvábím', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ryor', 'Výživný Krém Exclusive', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Bed Head by TIGI', 'Dirty Secret Instant Refresh Dry Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Tory Burch', 'Divine Moon Eau De Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Aveeno', '1% Hydrocortisone Anti-Itch Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Peter Thomas Roth', 'Acne Clearing Wash', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Laneige', 'Moisturizing Cream Cleanser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Laneige', 'Skin Veil Luminizing Base with SPF50', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Vichy', 'Liftactiv Supreme', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Armani Beauty', 'Luminous Silk Perfect Glow Flawless Oil-Free Foundation', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Skinfood', 'Sunflower Airy Sun Stick SPF 50+ PA++++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ryor', 'Výživný Krém S Přírodními Oleji', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Neutrogena', 'Deep Clean Invigorating Foaming Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kérastase', 'Discipline Heat Protecting Leave-In Treatment For Frizzy Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ligne St Barth', 'Extra Mild Shampoo Spirulina', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Aveeno', 'Skin Relief Intense Moisture Repair Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Elvive Repairing Shampoo with Protein', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Marie-Stella-Maris', 'No.73 Poivre Noir Frais Body Wash', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Elvive Extraordinary Oil Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Schwarzkopf Professional', 'OSIS+ TOPPED UP 1 Gentle Hold Mousse', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('KIKO Milano', 'Smart Charge Drops', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Verb', 'Dry Shampoo for Dark Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Rénergie Lift Multi-Action Eye', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Missha', 'All Around Safe Block Waterproof Sun Milk SPF50+/PA++++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soap & Glory', 'Smoothie Star Exfoliating Breakfast Body Scrub', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dove', 'Men+Care Clean Comfort Body and Face Wash', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Aqua Sensation Invigorating Day Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Joico', 'Zero Heat Air Dry Styling Crème For Fine/Medium Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Queen Helene', 'Cocoa Butter Hand & Body Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Neutrogena', 'Ultra Light Face Cleansing Oil & Makeup Remover', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Cetaphil', 'Moisturizing Relief Body Wash', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Body Shop', 'Vitamin E Moisture-Protect Emulsion SPF30', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Chanel', 'Bleu De Chanel After Shave Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Botanics', 'Organic Day Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Esfolio', 'Rose Essence Mask Sheet', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Creed', 'Aventus Shower Gel', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Volume Million Lashes', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Sublime Bronze Self-Tanning Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Paul Mitchell', 'Original Awapuhi Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Peter Thomas Roth', 'Hungarian Thermal Water Mineral-Rich Atomic Heat Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sebastian Professional', 'Whipped Crème Hair Styling Cream for Curly & Wavy Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Mielle Organics', 'Babassu Conditioning Sulfate-Free Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Skinfood', 'Lettuce and Cucumber Watery Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sudocrem', 'Antiseptic Healing Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Missha', 'M Perfect Cover BB Cream SPF 42', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Eucerin', 'Daily Protection Face Lotion Broad Spectrum SPF 30', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('StriVectin', 'Peptight™ Tightening Neck Serum Roller', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Suave', 'Invisible Solid Antiperspirant Deodorant - Cocoa Butter & Shea', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('It’s a 10', 'Silk Express Miracle Silk Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Yves Saint Laurent', 'Touche Eclat All-In-One Glow Foundation - B40 Sand', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Amika', 'Supernova Moisture and Shine Cream', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Exuviance', 'Achieve Lift Volumizing Concentrate', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Face Shop', 'Rice Water Bright Cleansing Wipes', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Armani Beauty', 'Power Fabric Foundation SPF 25 - 6.25 Medium to Tan with Neutral Undertone', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Amika', 'Supernova Blonde Moisture and Shine Cream', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nexxus', 'Ultralight Smooth Weightless Protection Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Tonique Douceur Softening Hydrating Toner with Rose Water', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Aquolina', 'Pink Sugar Eau de Toilette', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('VZK', 'Soothing Cream for Problematic Skin', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Essano', 'Vitamin C Brightening SPF15 Moisturiser', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Avon Products', 'Aromatherapy Overnight Face Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Q10 Power Anti-Wrinkle + Pore Minimising Day Cream SPF15', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Botanics', 'Shine Away Day Cream - SPF 15', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Iope', 'Men Anti-Aging Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Matrix', 'Unbreak My Blonde Sulfate-Free Strengthening Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nexxus', 'Humectress Ultimate Moisture Conditioner for Dry Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Holika Holika', 'Daily Fresh Olive Lip & Eye Remover', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Britney Spears Fragrances', 'VIP Private Show Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Teint Idole Ultra 24H Long Wear Matte Foundation - 210', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('REDKEN', 'Acidic Bonding Concentrate Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Paul Mitchell', 'Super Skinny Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Raw Sugar', 'Simply Hand Wash Lemon Sugar', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dr. Hauschka', 'Melissa Day Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Tazorac', 'TAZORAC (tazarotene) Cream, 0.1%', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Purify Bio Aloe Vera Organic Rice Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Vaseline', 'Rosy Tinted Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Bumble and bumble.', 'Bond-Building Repair Shampoo', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Chanel', 'Coco Mademoiselle Eau de Parfum Spray', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Creme Facial Nutritivo', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Joico', 'HydraSplash Replenishing Leave-In', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', 'Regenerating Face Mask with Snail Extract', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Propyless', 'Kutan Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Hidratante Facial Noturno', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Eucerin', 'Redness Relief Night Creme', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Britney Spears Fragrances', 'Electric Fantasy Eau de Toilette', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Himalaya', 'Moisturizing Argan Oil Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Charms Cosmetic Skincare', 'Hydra Fresh Tinted Moisturiser SPF50 Broad Spectrum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Summers Laboratories Inc', 'Summers Laboratories Moisture-All', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Raw Sugar', 'Simply Hand Wash Vanilla Bean + Sugar', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Flower Beauty by Drew', 'Fight The Light Blue Light Protection Mist', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('SCINIC', 'All Day Fine Pore Mint Paste', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Formula 10.0.6', 'One Smooth Operator Pore Clearing Face Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Dermo-Expertise Eye Makeup Remover', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sunsense', 'Sun Protection Lip Balm SPF 50', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dove', 'Men+Care Deep Clean + Facial Cleanser Exfoliating Face Wash', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kérastase', 'Discipline Smoothing Hair Mask for Frizzy Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('Glossier', 'Perfecting Skin Tint', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Que Bella', 'Relaxing Lavender Mud Face Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Tom Ford', 'Shade and Illuminate Soft Radiance Foundation SPF 50', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('LUSH', 'Marilyn Hair Treatment', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Delicious Drop Lip Balm SPF 11 - Peach & Vanilla', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ChapStick', 'Original Chapstick', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Generic Value Products', 'Blonde Leave In Treatment Compare to It’s a 10 Miracle Leave In for Blondes', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soapbox', 'Sea Minerals & Blue Iris Gentle Moisture Liquid Hand Soap', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Revolution Beauty', 'GLOW Splendour Ultra Matte Bronzer - Light', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('LUSH', 'Lemony Flutter Cuticle Butter', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Eau Thermale Avène', 'Cicalfate LIPS Restorative Lip Cream', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Bed Head by TIGI', 'Recovery Moisturising Conditioner for Dry Hair', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ESPA', 'Clarifying Clay Mineral Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('SexyHair', 'Healthy Sexy Hair Strengthening Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Finesse', 'Restore + Strengthen Normal Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Bienfait Multi-Vital Eye Sunscreen Broad Spectrum SPF 30', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kérastase', 'Elixir Ultime Le Fondant Conditioner', 'hair', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Britney Spears Fragrances', 'Hidden Fantasy Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('SkinCeuticals', 'A.G.E. Interrupter', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'HydraFresh Toner', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Fresh', 'Umbrian Clay Pore Purifying Face Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Britney Spears Fragrances', 'Fantasy in Bloom Eau de Toilette', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Aveeno', 'Ultra-Calming Fragrance-Free Daily Facial Moisturizer with SPF 15', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Rimmel London', 'Stay Glossy Lip Gloss - Seduce Me', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Blistex', 'Medicated SPF 15 Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Occitane', 'Shea Butter Hand Cream', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Vaseline', 'Illuminate Me Shimmering Body Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('A''Pieu', 'Deep Clean Cleansing Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('By Terry', 'Tea to Tan Face and Body Bronzer', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Decorte', 'Prime Latte Essential Softening Milk', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sally Hansen', 'Cuticle Massage Cream', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'Total Temptation Washable Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'Lash Sensational Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soapbox', 'Coconut Milk & Sandalwood Deep Moisture Liquid Hand Soap', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Chloé Fragrances', 'Chloé Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', 'Roses of Bulgaria and Hyaluron Eye Contour Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soap & Glory', 'Scrub Your Nose In It Two-Minute T-Zone Detox Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('LUSH', 'Ocean Salt Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Blistex', 'MedPlus Tiegel', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ChapStick', 'Classic Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Body Shop', 'Drops of Youth™ Youth Fresh Emulsion SPF20 PA+++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Raw Sugar', 'Simply Hand Wash Raw Coconut + Mango', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Anna Sui', 'Cleansing Water', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Blistex', 'Ultra Lip Balm SPF50+', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soapbox', 'Citrus & Peach Rose Reviving Moisture Liquid Hand Soap', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dove', 'DermaSpa Summer Revived Self Tanner Body Lotion Medium to Dark Skin', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Granado', 'Creme Para as Mãos Granado Pink', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Philosophy', 'Purity Made Simple Facial Cleansing Gel & Eye Makeup Remover', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shiseido', 'After Sun Intensive Recovery Emulsion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Prairie', 'Cellular Mineral Face Exfoliator', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('DR''s Secret', 'Moisturizer 6', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Renee Rouleau Skin Care', 'Night Time Spot Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Burt''s Bees', 'Men''s Facial Scrub', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ISDIN', 'Ureadin Hand Cream', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Britney Spears Fragrances', 'Circus Fantasy Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nuxe', 'Exfoliating Mask, Insta-Masque', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Revitalift Hyaluronic Acid Face Toner', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Merle Norman', 'Gentle Polish', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Clarins', 'Super Restorative Remodelling Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Highlighting Drops - Glow Mon Amour Sparkling Love', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('KUMANO COSME', 'Deve Olive & Argan Cleansing Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ariana Grande Fragrances', 'Ari Eau de Parfum', 'fragrance', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Roche-Posay', 'Toleriane Mascara Volume', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Max Factor X', '2000 Calorie Dramatic Volume Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Clarins', 'Hydrating Toning Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'The Falsies Lash Lift Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Prairie', 'Platinum Rare Haute-Rejuvenation Elixir', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('May Coop', 'Vine Expert Serum "Anti-Aging"', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Q10 plus Anti-Wrinkle Night Moisturizer', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dr Botanicals', 'Kiwi Superfood Cooling Eye Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Dermo-Expertise Eye Defense Eye Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'The Falsies Lash Mask', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Pipette', 'Overnight Brightening Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sukin', 'Rich Moisture Facial Masque', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('TONYMOLY', 'I''m Honey Deep Moisture Rescue Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Eucerin', 'ProACNE Solution Toner', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Prairie', 'Platinum Rare Haute-Rejuvenation Eye Elixir', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Hada Labo', 'Kouji Treatment Eye Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Romand', 'Juicy Lasting Tint - #06 Fig Fig', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Burt''s Bees', 'Aloe & Coconut Oil After Sun Soother', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nature Republic', 'Forest Garden Chamomile Cleansing Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('VZK', 'Face Soothing Mist', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nip + Fab', 'Dragon’s Blood Fix Plumping Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Hermès', 'Les Mains Hermès Enamel Base Coat', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Darphin', 'SKIN MAT Purifying Aromatic Clay Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Prairie', 'Cellular Refining Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ISDIN', 'Ureadin Gel Cream Eye Contour', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Clarins', 'Toning Lotion With Iris', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', '2-Step Lip Kit with Raspberry and Collagen', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sisley', 'Floral Toning Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Milk Makeup', 'Lip + Cheek Cream Blush Stick', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('HoliFrog', 'Owel Multi-Peptide Eye Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Pond''s', 'Makeup Remover Cleansing Balm', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Fresh', 'Sugar Lip Polish Exfoliator', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'Sky High Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nivea', 'Purifying Toner - Ocean Algae', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('By Terry', 'Baume de Rose Liquid Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Lash Idôle Mascara Gift Set (Limited Edition)', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Floss Beauty', 'My Everyday Eyeshadow', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Biopelle', 'Dark Circle Relief Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('L''Oreal', 'Pure Clay Mask Purify & Matify', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Mario Badescu', 'Rose Hips Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Fenty Beauty', 'Cherry Treat Conditioning Lip Oil', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('W7', 'Sweet Dreams Overnight Lip Mask', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ecological Formulas', 'Melazepam', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('St. Moriz', 'APF Ultra Finish', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Perricone MD', 'Multi-Action Overnight Intensive Firming Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Vitamins and Sea beauty', 'Sea Lavender Chamomile Overnight Hydration Sleep Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('COLLISTAR Milano', 'Body-Legs Magic Drops - Concentrated Self-Tanner', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Romand', 'Juicy Lasting Tint Bare Juicy Series - Nucadamia', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Mamonde', 'Age Control Power Lift Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'Lash Discovery Waterproof Mascara', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'Pure Clay Mask Clear & Comfort', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('TAN-LUXE', 'The Gradual Illuminating Gradual Tan Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Glossier', 'Generation G - Jam', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Naobay', 'Intensive Mask For Oily Skin', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kelsey', 'Morn to Eve Global Protection Concentrate', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('e.l.f. cosmetics', 'Expert Liquid Liner - Midnight', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Face Shop', 'Real Nature Rice Face Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Romand', 'Juicy Lasting Tint Bare Juicy Series - Pomelo Skin', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Proactiv', 'Blackhead Dissolving Gel', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Jergens Skincare', 'Natural Glow Instant Sun Body Mousse', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Prasco', 'Metronidazole Topical Cream 0.75%', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sulwhasoo', 'Concentrated Ginseng Renewing Eye Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sulwhasoo', 'Overnight Vitalizing Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Yves Saint Laurent', 'The Slim Velvet Radical Matte Lipstick', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sulwhasoo', 'Essential Balancing Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Miqura', 'Décolleté Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dr. Brandt Skincare', 'Do Not Age with Dr. Brandt Transforming Pearl Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Mer', 'The Regenerating Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Christian Louboutin', 'Rouge Louboutin Velvet Matte - 001M', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('skinChemists', 'Rose Quartz Lip Plump', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', 'Cannabis Moisturizing Eye Contour Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Erisan', 'Erisan+ Prebioottisen Yövoide', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('innisfree', 'Tangerine Brightening & Pore-Refining Sleeping Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('St. Tropez', 'Ashley Graham Limited Edition Ultimate Glow Kit', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('StriVectin', '360° Tightening Eye Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lumene', 'LÄHDE Oxygen Recovery 72h Hydra Gel Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Saltee', 'Active Sun Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('OPI', 'Expert Touch Lacquer Remover', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sephora Collection', 'Eye Mask Pomegranate', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Saltee', 'Sea & Sun Lotion', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('I''m Sorry For My Skin', 'Jelly Mask - Brightening', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Burt''s Bees', '100% Natural Conditioning Lip Scrub with Exfoliating Honey Crystals', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'REVITALIFT Pro Youth Mask (Plumping)', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Rose Inc', 'Satin Lip Color Refillable Hydrating Lipstick', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Ulta', 'Holiday Party Animals Sheet Masks - Owl', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('La Mer', 'The Hydrating Facial', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('L''Oreal', 'REVITALIFT Pro Youth Mask (Lifting)', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Symbiosis London', 'Heroes Collection - Tightening & Resplendent Eye Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('Nature Republic', 'Bee Venom Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('TONYMOLY', 'Fresh to Go Mask Sheet - Grape', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Vichy', 'Neovadiol Night Compensating Complex', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Avène', 'Soothing Moisture Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Laneige', 'White Dew Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('OPI', 'Natural Nail Strengthener', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Miguhara', 'Sheet Mask for Aqua Moisturizing Step 1', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Thank You Farmer', 'True Water Deep Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Garnier', 'Moisture Bomb The Super Hydrating Sheet Mask - Soothing', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Huxley', 'Secret of Sahara Sleep Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Etude House', 'Moistfull Collagen Sleeping Pack', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('OPI', 'Natural Nail Base Coat', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Cutex', 'Ultra-Powerful Nail Polish Remover', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Jones Road', 'The Oil Stick', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Unicorn Glow', 'Luminous Lip Gloss 01 Diamond', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Institut Esthederm', 'Eau Cellulaire Lotion Essence', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('May Coop', 'Raw Sauce', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sisley', 'Ecological Compound Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Laneige', 'Lip Sleeping Mask EX - Apple Lime', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Revlon', 'Kiss Exfoliating Lip Balm - Sugar Mint', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Zymogen', 'Nutri Active Ferment Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Nature Republic', 'Bulgarian Rose Moisture Emulsion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dior', 'Backstage Rosy Glow Blush - 001 Pink', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Physician''s Formula', 'Rosé All Stay Illuminating Setting Spray', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sulwhasoo', 'First Care Activating Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('REN Clean Skincare', 'Overnight Glow Dark Spot Sleeping Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Maybelline', 'Facestudio Master Strobing Stick Highlighter - 200 Medium-Nude Glow', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dior', 'Rouge Blush - 439 Why Not', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dermalogica', 'Age Smart Overnight Repair Serum', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Anko', 'Overnight Lip Mask - Watermelon Extract', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Esker', 'Restorative Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Everyday Oil', 'Mainstay', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sally Hansen', 'Hard as Nails Nail Hardener', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Dior', 'Backstage Rosy Glow Blush - 004 Coral', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', 'Cannabis Intensive Soothing Night Face Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', 'Snail Extract Night Cream Concentrate', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Muji', 'All in One Essence - Sensitive Skin', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Neutrogena', 'Deep Moisture Night Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Neutrogena', 'Hydro Boost Night Concentrate', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Wishful', 'Get Even Rose Face Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Crazy Skin', 'Trouble Care Sleeping Cream (Upgrade)', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Laneige', 'Time Freeze Sleeping Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('OPI', 'Nail Envy Nail Strengthener - Original', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Skinfood', 'Royal Honey Propolis Pore Chilling Essence', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('ApotheCARE Essentials', 'Essentials PhytoQuench Replenishing Sleeping Face Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Burt''s Bees', 'Renew Natural Hydrogel Eye Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shiseido', 'White Lucent Anti-Dark Circles Eye Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Pixi Beauty', 'Hydrating Milky Mist', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Kjaer Weis', 'Facial Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Guerlain', 'Abeille Royale Youth Watery Anti-Aging Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);

insert into public.catalog_products (brand, name, category, source, active_flag)
values
  ('Simple Skincare', 'Water Boost Skin Quench Sleeping Cream', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Cutex', 'Non-Acetone Ultra-Care Nail Polish Remover', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lancôme', 'Hydra Zen Beauty Facial Essence', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shangpree', 'Gold Black Pearl Eye Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Zoya', 'Naked Manicure Naked Base', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shiseido', 'Benefiance Wrinkle Smoothing Day Emulsion SPF 30 PA+++', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sephora Collection', 'Eye Mask Pearl', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Cortizone-10', 'Maximum Strength 1% Hydrocortisone Anti-Itch Creme with Aloe', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Yves Saint Laurent', 'Radiant Touch Highlighter & Concealer', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sephora Collection', 'Hempseed Multi-Purpose Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Wet n Wild', 'Save The Day Lip Mask', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Chanel', 'La Base Protective and Smoothing Nail Treatment', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Lisa Eldridge', 'Elevated Glow Highlighter', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Elemis', 'Pro-Collagen Rose Facial Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Essie', 'Hard to Resist Advanced Nail Strengthener', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Estée Lauder', 'Swiss Performing Extract', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Clarins', 'Super Restorative Treatment Essence', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Soap & Glory', 'Original Pink Get Enriched Quick Nourishing Bath & Body Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('O’Keeffe’s', 'Lip Repair Night Treatment', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sephora Collection', 'Coconut Multi-Purpose Oil', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Sally Hansen', 'Salon Gel Polish Acetone Remover', 'other', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('A''Pieu', 'Honey & Milk Lip Scrub', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Saie', 'Sun Melt Natural Cream Bronzer', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Petitfee & Koelf', 'Pearl Shea Butter Hydrogel Eye Patch', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Flower Beauty by Drew', 'Blush Bomb Color Drops', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('First Aid Beauty', 'Ultra Repair Intensive Lip Balm', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Estée Lauder', 'RE-NUTRIV Softening Lotion', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Patrick Ta', 'Major Glow Softening Lip Masque', 'lip', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Patrick Ta', 'Major Beauty Headlines - Double-Take Crème & Powder Blush', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Flower Beauty by Drew', 'Flower Pots Powder Blush', 'face', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('The Body Shop', 'Drops of Youth™ Youth Bouncy Eye Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Avoskin', 'Eye Gel Mask with Black Caviar Extract ''Luxurious Renewal''', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Victoria Beauty', '24K Gold Luxurious Silk Touch Under Eye Patches', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Shangpree', 'Ginseng Berry Eye Mask', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Mizon', 'Collagen Eye Gel Patch', 'skincare', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Essence', 'Disney Princess Jasmine False Lashes 02 Courage', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Essence', 'Disney Princess Mulan False Lashes 03 Loyalty', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true),
  ('Essence', 'Disney Princess Rapunzel False Lashes 01 Kindness', 'eye', 'Cosmetics datasets (kingabzpro, Kaggle, MIT license)', true);
