import { RepurchaseVerdict } from '../../mocks/types';

export const emptiesStrings = {
  progressTitle: 'My Progress',
  progressAccessibilityLabel: 'My Progress and your private empties archive',
  progressRingLabel: (percent: number) => `${percent}% finished`,
  progressRingAccessibility: (percent: number) => `${percent}% of your products are finished`,
  progressFinishedCount: (count: number) => `${count} finished`,
  progressStreak: (count: number) => `${count}-day logging streak`,
  progressInRotationCount: (count: number) => `${count} in rotation`,
  progressUnopenedCount: (count: number) => `${count} unopened`,
  progressStatusAccessibilityLabel: (inRotation: number, unopened: number, finished: number) =>
    `Product status: ${inRotation} in rotation, ${unopened} unopened, ${finished} finished`,
  archiveTitle: 'Your Empties',
  archiveAccessibilityLabel: 'Your private empties archive',
  fallbackProductName: 'Finished product',
  cardAccessibilityLabel: (brand: string, name: string, verdict: string) =>
    `${brand} ${name}. Repurchase: ${verdict}.`,
  monthsInUse: (months: number) => `${months} ${months === 1 ? 'month' : 'months'} in use`,
  repurchaseLabel: 'Repurchase',
  repurchaseVerdicts: {
    yes: 'Yes',
    maybe: 'Maybe',
    no: 'No',
  } satisfies Record<RepurchaseVerdict, string>,
  noEmptiesTitle: 'Your empties will gather here',
  noEmptiesMessage: 'When you finish a product, it will become part of your private shelf.',
  emptyStateAccessibilityLabel: 'You have no finished products yet. Your empties will gather here.',
  loadingArchive: 'Loading your progress',
  loadingArchiveAccessibilityLabel: 'Loading your private empties archive',
  archiveErrorTitle: 'Your progress needs another moment',
  archiveErrorMessage: 'Please try again. Your finished products are still yours.',
  archiveErrorAccessibilityLabel: 'Your progress could not be loaded. Try again.',
  finishConfirmTitle: 'Finished this one?',
  finishConfirmMessage:
    'You can celebrate this little win and save it to your private empties shelf.',
  finishConfirmAction: 'Yes, I finished it',
  finishConfirmAccessibilityLabel: 'Confirm that you finished this product',
  finishNotFoundTitle: 'This product is not available',
  finishNotFoundMessage: 'Please return to your inventory and try again.',
  finishProductAccessibilityLabel: (brand: string, name: string) => `Finish ${brand} ${name}`,
  celebrationSparkles: '✦  ✧  ✦  ✧  ✦  ✧  ✦  ✧  ✦',
  celebrationBurstSparkles: [
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
    '✦',
    '✧',
  ],
  celebrationCompletionMark: '✓',
  celebrationTitle: 'You finished it!',
  celebrationMessage: 'A thoughtful finish is something to feel good about.',
  celebrationProductLabel: 'Your finished product',
  celebrationProductShade: (shade: string) => `Shade: ${shade}`,
  celebrationProductAccessibilityLabel: (brand: string, name: string) =>
    `Finished product: ${brand} ${name}`,
  celebrationContinue: 'Add a quick note',
  celebrationContinueAccessibilityLabel: 'Continue to the repurchase review',
  finishCancelAction: 'Not finished yet',
  finishCancelAccessibilityLabel: 'Return to Progress without finishing this product',
  reviewTitle: 'Would you repurchase it?',
  reviewMessage: 'A quick note can help future you remember what worked.',
  reviewInputLabel: 'A note for future you',
  reviewInputPlaceholder: 'What did you think?',
  reviewVerdictLabel: 'Your verdict',
  reviewSkip: 'Skip for now',
  reviewSkipAccessibilityLabel: 'Skip the review and save Maybe as your verdict',
  reviewSave: 'Save to my empties',
  reviewSaveAccessibilityLabel: 'Save this finished product to your private empties archive',
  reviewCancelAccessibilityLabel: 'Return to Progress without saving this finished product',
  reviewDefaultVerdictNote: 'Skipping saves “Maybe” for now.',
  finishErrorTitle: 'Your finish was not saved yet',
  finishErrorMessage: 'Please try again when you are ready.',
  finishSavedTitle: 'Saved to your empties',
  finishSavedMessage: 'Your private shelf is ready whenever you want to look back.',
  finishSavedAction: 'View my progress',
  finishSavedAccessibilityLabel: 'View your progress and private empties archive',
  developerPreviewTitle: 'Finish-flow preview',
  developerPreviewMessage:
    'Choose a test product. Saving it will mark it finished in your own account.',
  developerPreviewAction: (brand: string, name: string) => `Preview finish: ${brand} ${name}`,
  developerPreviewAccessibilityLabel: (brand: string, name: string) =>
    `Preview the finish flow for ${brand} ${name}`,
  developerSamplePreviewMessage:
    'No test products are available yet. This sample lets you preview the flow without saving anything.',
  developerSamplePreviewAction: 'Preview a sample finish',
  developerSamplePreviewAccessibilityLabel: 'Preview a sample finish without saving data',
  previewOnlyMessage: 'Preview only — this will not change your products or archive.',
};
